//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupImage
    {
        public int image_id { get; set; }
        public int group_id { get; set; }
        public byte[] image_data { get; set; }
        public string image_name { get; set; }
        public Nullable<int> upload_order { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
    
        public virtual TripGroup TripGroup { get; set; }
    }
}
