//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HikingDBEntities1 : DbContext
    {
        public HikingDBEntities1()
            : base("name=HikingDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MountainTrail> MountainTrails { get; set; }
        public virtual DbSet<GroupImage> GroupImages { get; set; }
        public virtual DbSet<TripGroup> TripGroups { get; set; }
    }
}
