//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MountainTrail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MountainTrail()
        {
            this.TripGroups = new HashSet<TripGroup>();
        }
    
        public int ID { get; set; }
        public string badge { get; set; }
        public int walk_days { get; set; }
        public string location { get; set; }
        public string mt_name { get; set; }
        public int diff { get; set; }
        public decimal dist_km { get; set; }
        public int time_min { get; set; }
        public int ascend_m { get; set; }
        public int descend_m { get; set; }
        public string trail_cond { get; set; }
        public string route_type { get; set; }
        public int min_alt_m { get; set; }
        public int max_alt_m { get; set; }
        public string mt_range { get; set; }
        public byte park_permit { get; set; }
        public byte mt_permit { get; set; }
        public string TripDetails { get; set; }
        public string region { get; set; }
        public string TripSchedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripGroup> TripGroups { get; set; }
    }
}
