//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripGroup()
        {
            this.GroupImages = new HashSet<GroupImage>();
        }
    
        public int group_id { get; set; }
        public int mt_id { get; set; }
        public int user_id { get; set; }
        public string group_name { get; set; }
        public System.DateTime activity_date { get; set; }
        public string meeting_time { get; set; }
        public string meeting_location { get; set; }
        public string custom_schedule { get; set; }
        public string leader_message { get; set; }
        public Nullable<int> max_participants { get; set; }
        public Nullable<int> current_participants { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> include_transport { get; set; }
        public Nullable<bool> include_accommodation { get; set; }
        public Nullable<bool> include_guide { get; set; }
        public Nullable<bool> include_insurance { get; set; }
        public Nullable<bool> include_course { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupImage> GroupImages { get; set; }
        public virtual MountainTrail MountainTrail { get; set; }
        public virtual User User { get; set; }
    }
}
